"""Render the per-PR Kustomize overlay.

Phase 2 ships the shared ``k8s/base``; this module generates the overlay
directory for one pull request — a ``kustomization.yaml`` that points at the
base, sets the namespace, pins the image tag, and patches the ingress host.
"""

KUSTOMIZATION_TEMPLATE = """\
# Generated by previewctl — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {namespace}

resources:
  - {base}

images:
  - name: {image}
    newTag: {tag}

labels:
  - pairs:
      preview.env/platform: "true"
      preview.env/pr: "{pr}"
    includeSelectors: true

patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: {host}
"""


def render_kustomization(
    *,
    namespace: str,
    base: str,
    image: str,
    tag: str,
    pr: int,
    host: str,
) -> str:
    """Return the contents of the overlay ``kustomization.yaml``."""
    for field, value in {
        "namespace": namespace,
        "image": image,
        "tag": tag,
        "host": host,
    }.items():
        if not value or not value.strip():
            raise ValueError(f"{field} must be non-empty")
    if pr < 1:
        raise ValueError("pr must be a positive integer")
    return KUSTOMIZATION_TEMPLATE.format(
        namespace=namespace, base=base, image=image, tag=tag, pr=pr, host=host
    )


def preview_host(pr: int, domain: str) -> str:
    """Return the ingress host for a PR, e.g. ``pr-12.preview.example.com``."""
    if pr < 1:
        raise ValueError("pr must be a positive integer")
    domain = domain.strip().strip(".")
    if not domain:
        raise ValueError("domain must be non-empty")
    return f"pr-{pr}.{domain}"


def write_overlay(directory, content: str) -> None:
    """Write ``content`` as ``<directory>/kustomization.yaml``."""
    from pathlib import Path

    path = Path(directory)
    path.mkdir(parents=True, exist_ok=True)
    (path / "kustomization.yaml").write_text(content, encoding="utf-8")
